### ISSUE TITLE
BannerView.onViewableSuccess() 에서 NullPointException 발생

### ISSUE THREAD

**Issue by kimjunil** [adfit/adfit-android-sdk#10]
안녕하세요.
Adfit 사용중 특정 부분에서 에러가 빈번하게 발생하여 문의드립니다.

현재 Adfit, Admob, Cauly, DawinClick(구 t-ad, Syrup Ad) 등을 자체 라이브러리로 미디에이션하여 사용하고있습니다.
Fabric Crashlytics를 이용하여 크래시 리포팅을 받고있는데 아래와 같은 NullPointException이 빈번하게 발생합니다.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.kakao.adfit.ads.ba.BannerAdView$7.onViewableSuccess(BannerAdView.java:609)
       at com.kakao.adfit.common.b.r$2.handleMessage(ViewableCheck.java:400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
간헐적으로 발생하고 있는 에러이고, 재현이 잘 되지 않아 정확히 어떤 상황에서 발생하는 에러인지는 모르겠습니다.

BannerAdView.class파일을 따라가보니 난독화되어 정확히 알 순 없지만
```java
...
if (BannerAdView.this.y.vimpUrl.equals(var3)) {
    BannerAdView.this.y._vimpOk = true;
}
...
```
이 부분이 아닐까 의심이 됩니다.
혹시 Adfit 광고를 단독으로 사용하지 않을 경우 문제가 발생할 수 있나요?!

**Comment by kimjunil** [comment]
adfit SDK 3.0.2 버전입니다

**Comment by chanyhan** [comment]
제보 감사합니다. 다음 릴리즈에 방어코드를 추가하도록 하겠습니다.

**Comment by chanyhan** [comment]
@kimjunil 3.0.3 에 패치되었습니다.
