### ISSUE TITLE
Fragment에서 BannerAdView 사용 가능 할까요??

### ISSUE THREAD

**Issue by seochanhee** [adfit/adfit-android-sdk#27]
**버그 내용**
Fragment에서 BannerAdView 사용 가능 할까요??

**재현 방법**
ViewDataBinding을 사용하여 fragment layout xml에 BannerAdView 을 넣었더니 아래와 같이 크래시가 나는데
fragment에서 사용 불가능 한가요??

**Stacktrace**
```
Process: com.chanApps.waterroommap.dev, PID: 2541
    android.view.InflateException: Binary XML file line #85 in com.chanApps.waterroommap.dev:layout/fragment_recommend: Binary XML file line #85 in com.chanApps.waterroommap.dev:layout/fragment_recommend: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #85 in com.chanApps.waterroommap.dev:layout/fragment_recommend: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.chanApps.waterroommap.ui.base.fragment.BindingFragment.onCreateView(BindingFragment.kt:26)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
        at android.app.Activity.performStart(Activity.java:8096)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3688)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2218)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:8005)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
     Caused by: java.lang.IllegalArgumentException: Context must be Activity context!
        at com.kakao.adfit.ads.ba.BannerAdView.<init>(BannerAdView.kt:118)
        at com.kakao.adfit.ads.ba.BannerAdView.<init>(BannerAdView.kt:1)
2022-09-14 16:08:22.145 2541-2541/com.chanApps.waterroommap.dev E/AndroidRuntime:     at com.kakao.adfit.ads.ba.BannerAdView.<init>(Unknown Source:11)
        	... 42 more
```

**Comment by Unbalance09** [comment]
안녕하세요.
Fragment에서 BannerAdView 사용 가능하며, ViewDataBinding 사용도 가능합니다.
첨부해주신 Stacktrace 내용을 봐서는 Fragment 생성 시에 사용된 Context가 
Activity Context가 아니어서 생성에 실패한 것으로 보입니다.
Activity에 부착된 Fragment에서도 같은 오류가 발생한다면 
좀 더 자세한 상황 설명과 함께 다시 문의 부탁드립니다.
감사합니다.

**Comment by zach-ooo** [comment]
@seochanhee 
안녕하세요!
혹시 위 문제 해결하셨나요??
저도 똑같이 DataBindingUtil.inflate() 사용해서 activity내에 fragment를 띄우고 있는데요
BannerAdView 생성시 같은 에러가 발생합니다.

어느 부분에서 Context가 아닌 Activity context를 이용해야하는지 모르겠어서
혹시 해결하셨다면 어떻게 해결하셨는지 여쭤봅니다!

@Unbalance09 
안녕하세요!
혹시 위와 같은 상황인데 확인해볼 부분이 있을까요??

**Comment by Unbalance09** [comment]
@zach-ooo 
안녕하세요.
DataBindingUtil.inflate()을 호출하실 때 사용하시는 LayoutInflater의 context가 Activity context가 맞는지 확인 부탁드립니다.
```kotlin
val inflater: LayoutInflater
val isActivityContext = inflater.context is Activity
val contextClassName = inflater.context.javaClass.name
```

Activity context가 아니라면 사용된 Context 종류와 DataBindingUtil.inflate() 호출 위치, 
Fragment 생성 방식 등 추가 정보와 함께 다시 문의 부탁드립니다.
감사합니다.

**Comment by zach-ooo** [comment]
@Unbalance09 
답변 감사합니다!
override fun onCreateView() 에서 받은 LayoutInflater를 그대로 사용했는데
class dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper
여서 제대로 로드가 안 됐었습니다.

activity의 layoutInflater를 가져와서 사용하니 정상적으로 로드되는 것 확인했습니다.

감사합니다.
