### ISSUE TITLE
IABLayout 비정상 종료 이슈 발생

### ISSUE THREAD

**Issue by tkddn9316** [adfit/adfit-android-sdk#33]
**버그 내용**
안녕하세요.
현재 운영 중인 앱에 비정상 종료가 감지되어 확인 부탁드립니다.
위치는 kakao adfit 내부에 있는 IABLayout로 추정됩니다.
Crashlytics 참고하여 로그 첨부합니다.

**재현 방법**
불명

**Stacktrace**
```
Fatal Exception: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %/w
       at java.net.URLDecoder.decode(URLDecoder.java:214)
       at java.net.URLDecoder.decode(URLDecoder.java:143)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.a(SourceFile:63)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.b(SourceFile:26)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.b(SourceFile:2)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout$b.shouldOverrideUrlLoading(SourceFile:8)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-672310733:124)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:187)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:9063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**재현환경:**
 - Device: Galaxy S24+
 - OS: android 14
 - Version: adfit_version = '3.16.0'

**추가 정보**
문제와 관련해 추가적으로 기재할 내용이 있다면 추가해주세요

**Comment by nairs77** [comment]
안녕하세요. 우선 제보해 주셔서 정말 감사합니다.
로그에서 확인 되듯이, 해당 광고의 랜딩 처리시 URL에 escape 처리가 잘못되어 발생된 오류 입니다.
해당 광고 랜딩을 수정하도록 요청을 드렸습니다. 

다시 한번 제보해 주셔서 감사합니다.

**Comment by tkddn9316** [comment]
안녕하세요. 현재 동일한 에러가 계속하여 발생하고 있습니다. 다시 한번 확인 부탁드립니다.

```
Fatal Exception: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %/w
       at java.net.URLDecoder.decode(URLDecoder.java:178)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.a(SourceFile:63)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.b(SourceFile:26)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout.b(SourceFile:2)
       at com.kakao.adfit.common.inappbrowser.widget.IABLayout$b.shouldOverrideUrlLoading(SourceFile:8)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-699813533:117)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:197)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Unbalance09** [comment]
안녕하세요
지난주에 배포된 [v3.19.3](https://github.com/adfit/adfit-android-sdk/releases/tag/v3.19.3)에 해당 오류가 재발하지 않도록 처리된 코드가 포함되어 있습니다.
최신 버전 SDK로 업데이트 부탁드리며, [v3.19.3](https://github.com/adfit/adfit-android-sdk/releases/tag/v3.19.3) 이후 버전을 사용한 앱에서도 문제가 발생한다면 다시 말씀 부탁드립니다.
제보 감사합니다.
